/* run as sysdba */
CREATE OR REPLACE DIRECTORY MEDIA_DIR AS '/home/oracle/mdb_cbr/music';
GRANT READ,WRITE ON DIRECTORY MEDIA_DIR TO MDB;
COMMIT;

CREATE OR REPLACE DIRECTORY IMAGES_DIR AS '/home/oracle/mdb_cbr/images';
GRANT READ, WRITE ON DIRECTORY IMAGES_DIR TO MDB;
COMMIT;

CREATE OR REPLACE DIRECTORY EXPORTS_DIR AS '/home/oracle/mdb_cbr/exports';
GRANT READ, WRITE ON DIRECTORY EXPORTS_DIR TO MDB;
COMMIT;
/* end run as sysdba */

/* enable output */
SET SERVEROUTPUT ON;

/*check directories have been created succesfully*/
SELECT * FROM DBA_DIRECTORIES 
WHERE DIRECTORY_NAME = 'MEDIA_DIR' OR DIRECTORY_NAME = 'IMAGES_DIR' OR DIRECTORY_NAME = 'EXPORTS_DIR';



