/* users table creation */
CREATE TABLE USERS (
  USERNAME VARCHAR2(50 CHAR) NOT NULL, 
  FIRST_NAME VARCHAR2(50 CHAR), 
  LAST_NAME VARCHAR2(50 CHAR), 
  CONSTRAINT USERS_PK PRIMARY KEY (USERNAME) ENABLE
) LOGGING TABLESPACE "USERS" PCTFREE 10 INITRANS 1 STORAGE (BUFFER_POOL DEFAULT);


/* artists table creation */
CREATE TABLE ARTISTS (
  NAME VARCHAR2(50 CHAR) NOT NULL, 
  NATIONALITY VARCHAR2(2 BYTE), 
  GENRE VARCHAR2(50 CHAR), 
  CONSTRAINT ARTISTS_PK PRIMARY KEY (NAME) ENABLE
) LOGGING TABLESPACE "USERS" PCTFREE 10 INITRANS 1 STORAGE (
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT
);


/* albums table creation */
CREATE TABLE ALBUMS (
  NAME VARCHAR2(50 CHAR) NOT NULL, 
  ARTIST VARCHAR2(50 CHAR), 
  RELEASE_YEAR NUMBER, 
  COVER ORDSYS.ORDIMAGE, 
  CONSTRAINT ALBUMS_PK PRIMARY KEY (NAME) ENABLE
) LOGGING TABLESPACE "USERS" PCTFREE 10 INITRANS 1 STORAGE (
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT
);
ALTER TABLE 
  ALBUMS 
ADD 
  CONSTRAINT FK_ALBUMS_ARTIST FOREIGN KEY (ARTIST) REFERENCES ARTISTS (NAME) ENABLE;


/* songs table creation */
CREATE TABLE SONGS (
  TITLE VARCHAR2(50 BYTE) NOT NULL, 
  ARTIST VARCHAR2(50 CHAR) NOT NULL, 
  ALBUM VARCHAR2(50 CHAR) NOT NULL, 
  TRACKFILE ORDSYS.ORDAUDIO, 
  ID NUMBER, 
  CONSTRAINT SONGS_TABLE_PK PRIMARY KEY (TITLE, ARTIST, ALBUM) ENABLE
) LOGGING TABLESPACE "USERS" PCTFREE 10 INITRANS 1 STORAGE (
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT
);
ALTER TABLE 
  SONGS 
ADD 
  CONSTRAINT SONGS_TABLE_UK1 UNIQUE (ID) ENABLE;
ALTER TABLE 
  SONGS 
ADD 
  CONSTRAINT FK_SONGS_ALBUM FOREIGN KEY (ALBUM) REFERENCES ALBUMS (NAME) ENABLE;
ALTER TABLE 
  SONGS 
ADD 
  CONSTRAINT FK_SONGS_ARTIST FOREIGN KEY (ARTIST) REFERENCES ARTISTS (NAME) ENABLE;


/* favs table creation */
CREATE TABLE FAVS (
  USERNAME VARCHAR2(50 CHAR) NOT NULL, 
  SONG_ID NUMBER NOT NULL, 
  PLAYLIST VARCHAR2(50 CHAR) NOT NULL, 
  CONSTRAINT FAVS_PK PRIMARY KEY (USERNAME, SONG_ID, PLAYLIST) ENABLE
) LOGGING TABLESPACE "USERS" PCTFREE 10 INITRANS 1 STORAGE (
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT
);
ALTER TABLE 
  FAVS 
ADD 
  CONSTRAINT FK_FAVS_SONG FOREIGN KEY (SONG_ID) REFERENCES SONGS (ID) ENABLE;
ALTER TABLE 
  FAVS 
ADD 
  CONSTRAINT FK_FAVS_USERNAME FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME) ENABLE;


/* playhistory table creation */
CREATE TABLE PLAYHISTORY (
  USERNAME VARCHAR2(20 BYTE) NOT NULL, 
  SONG_ID NUMBER NOT NULL, 
  PLAYCOUNT NUMBER DEFAULT 1, 
  CONSTRAINT PK_PLAYHISTORY PRIMARY KEY (USERNAME, SONG_ID) ENABLE
) LOGGING TABLESPACE "USERS" PCTFREE 10 INITRANS 1 STORAGE (
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT
);
ALTER TABLE 
  PLAYHISTORY 
ADD 
  CONSTRAINT FK_HIST_SONG FOREIGN KEY (SONG_ID) REFERENCES SONGS (ID) ENABLE;
ALTER TABLE 
  PLAYHISTORY 
ADD 
  CONSTRAINT FK_HIST_USERS FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME) ENABLE;
